config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get '/auth/googpic/callback' => 'sessions#create'
  resources :albums do
    resources :photos do
      resources :comments
    end
  end

end

app/models/album.rb
class Album
  def self.list(token)
    access_token = OAuth2::AccessToken.new(AuthClient.client, token)
    response = access_token.get 'https://picasaweb.google.com/data/feed/api/user/default', {parse: :json, mode: :query}

    doc = Nokogiri::XML(response.body)
    albums = {}

    doc.css('entry').each do |entry|
      albums.store(entry.at_xpath('gphoto:id').content, entry.at_css('title').content)
    end

    albums
  end
end

app/models/photo.rb
class Photo
  attr_accessor :id, :album_id, :thumb, :name, :count

  def initialize(hash={})
    @id = hash.fetch(:id)
    @album_id = hash.fetch(:album_id)
    @thumb = hash.fetch(:thumb)
    @name = hash.fetch(:name)
    @count = hash.fetch(:count)
  end

  def self.list(token, album_id, limit=3)
    response = access_token(token).get "https://picasaweb.google.com/data/feed/api/user/default/albumid/#{album_id}", {parse: :json, mode: :query}
    doc = Nokogiri::XML(response.body)
    photos = []

    doc.css('entry').each do |entry|
      photos << new({id: entry.at_xpath('gphoto:id').content,
                     album_id: entry.at_xpath('gphoto:albumid').content,
                     name: entry.at_css('title').content,
                     count: entry.at_xpath('gphoto:commentCount').content,
                     thumb: entry.xpath('media:group/media:thumbnail/@url').last.content
                    })
    end
    photos.take(limit)
  end

  def self.comments(token, album_id, photo_id)
    response = access_token(token).get "https://picasaweb.google.com/data/feed/api/user/default/albumid/#{album_id}/photoid/#{photo_id}?kind=comment", {parse: :json, mode: :query}
    doc = Nokogiri::XML(response.body)
    comments = []

    doc.css('entry').each do |entry|
      comments << entry.css('content').inner_text
    end

    comments
  end

  def self.add_comment(token, album_id, photo_id, comment)
    access_token = access_token(token)

    post_data = """<entry xmlns='http://www.w3.org/2005/Atom'>
      <content>#{comment}</content>
      <category scheme='http://schemas.google.com/g/2005#kind'
        term='http://schemas.google.com/photos/2007#comment'/>
    </entry>"""
    access_token.post("https://picasaweb.google.com/data/feed/api/user/default/albumid/#{album_id}/photoid/#{photo_id}",
                      body: post_data, headers: {'Content-Type' => 'application/atom+xml', 'Gdata-version' => '2'})
  end

  private

  def self.access_token(token)
    OAuth2::AccessToken.new(AuthClient.client, token)
  end

  def access_token(token)
    OAuth2::AccessToken.new(AuthClient.client, token)
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :authenticate

  def index
    @albums = Album.list(session[:token])
  end

  def show
    @photos = Photo.list(session[:token], params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def authenticate
    unless session[:token] && DateTime.strptime(session[:token_valid_until].to_s, '%s') > DateTime.now
      redirect_to root_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate

  def index
    @comments = Photo.comments(session[:token], params[:album_id], params[:photo_id])
    render json: @comments.to_json(root: false)
  end

  def create
    @comment = Photo.add_comment(session[:token], params[:album_id], params[:photo_id], params[:comment])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    begin
      token = AuthClient.get_token(params[:code])
      session[:token] = token.token
      session[:token_valid_until] = token.expires_at
    rescue OAuth2::Error => e
      raise "#{e}"
    end

    redirect_to albums_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/index.html.erb
<h3>Albums</h3>

<ul>
  <% @albums.each do |k, v| %>
    <li><%= link_to v, album_path(k) %></li>
  <% end %>
</ul>

app/views/albums/show.html.erb
<div class="row">
  <% @photos.each do |photo| %>
    <div class="col-md-6 pic-photo">
      <%= image_tag photo.thumb, class: 'img-rounded', alt: photo.name, title: photo.name %>

      <p>
        <%= link_to "Comments: #{photo.count}", '#', data: {toggle: 'modal', target: '#myModal', ids: "comment_#{photo.album_id}_#{photo.id}"} %>
      </p>

      <p>Leave Comment:</p>

      <%= form_tag album_photo_comments_path(photo.album_id, photo.id), remote: true do %>
        <%= text_area_tag 'comment', nil, id: "comment_#{photo.id}",size: '44x2', style: 'resize: none; margin-bottom: 5px' %>
        <%= submit_tag 'Submit', class: 'btn btn-primary btn-sm' %>
      <% end %>

      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title" id="myModalLabel">Comments</h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-primary btn-sm" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/comments/_modal.html.erb
<div class="modal fade" id="commentsModal" tabindex="-1" role="dialog" aria-labelledby="commentsModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="commentsModalLabel"><%= photo.name %></h4>
      </div>
      <div class="modal-body">
        <ul class="comments_<%= photo.id %>">
          <% photo.comments(session['token']).each do |f| %>
            <li><%= f %></li>
          <% end %>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/comments/create.js.erb
$("textarea#comment_<%= params[:photo_id] %>").val('');
alert('Comment added successfully!');

app/views/home/index.html.erb
<div class="jumbotron">
  <p>
    Create application with Ruby on Rails which will connect with google account and will show first three images from
    selected album (Picasa). User should be able to add comments.
  </p>

  <p>Flow should look:</p>

  <ol>
    <li>Login screen - where user can login via google account</li>
    <li>Album list - after login user will see list of all owned albums from Google Picasa account.</li>
    <li>Images view - user will see first three images from selected album.</li>
    <li>User is able to comment photo.</li>
  </ol>

  <br/>
  <p style="text-align: center"><%= link_to 'Sign in with Google', AuthClient.authorize_url, role: 'button', class: 'btn btn-lg btn-success' %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Googpic</title>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<div class="container">
  <div class="header">
    <h3 class="text-muted"><%= link_to 'Googpic', root_url %></h3>
  </div>

  <%= yield %>

  <div class="footer">
    <p>© Company 2014</p>
  </div>
</div>

</body>
</html>